services:
  php_7_4:
    build:
      context: ${WLNMP_ROOT_DIR}/hub/php_7_4
      args:
          TZ: ${WLNMP_TIMEZONE}
    volumes:
      # 代码卷
      - type: volume
        source: www_volume
        target: /wlnmp/www
      # 映射配置文件
      - type: bind
        source: ${WLNMP_SERVER_DIR}/php_7_4
        target: /wlnmp/php_7_4
        read_only: true